# Generated by Django 3.1 on 2020-08-17 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='CCS0PNV2', max_length=8, unique=True)),
                ('description', models.TextField(blank=True, default=None)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_till', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponSU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Admin', 'Admin'), ('Member', 'Member')], max_length=100, null=True)),
                ('code', models.CharField(default='AFCC7OX8TK', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_till', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralforMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='DFNG9N', max_length=6, unique=True)),
                ('description', models.TextField(default=None)),
                ('valid_from', models.DateField(default=datetime.date.today)),
                ('valid_till', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
