# Generated by Django 3.1 on 2020-08-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponadmin',
            name='code',
            field=models.CharField(default='TB5IQ3J7', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='couponsu',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='referralformember',
            name='code',
            field=models.CharField(default='1YZSTR', max_length=6, unique=True),
        ),
    ]
